ebpf build on kernel 5.18 (#12483)
kernel 5.18 define TASK_COMM_LEN in linux/sched.h and would need to be included for prebuild offset-guess

Stderr:

In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/percpu-rwsem.h:7:
In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/rcuwait.h:6:
In file included from /lib/modules/5.18.5-arch1-1/build/include/linux/sched/signal.h:7:
/lib/modules/5.18.5-arch1-1/build/include/linux/sched.h:282:2: error: expected identifier
        TASK_COMM_LEN = 16,
        ^
./pkg/network/ebpf/c/prebuilt/offset-guess.h:7:23: note: expanded from macro 'TASK_COMM_LEN'